name: trash_classifier_app
description: A trash classification app using TFLite
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  
  # 이미지 처리
  image_picker: ^1.1.2
  image: ^4.2.0
  
  # TFLite 최신 버전
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/trash_classifier.tflite
    - assets/models/labels.txt